# Generated by Django 4.2.20 on 2025-06-02 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="формат: '+79991234567' ", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
        ),
    ]
