# Generated by Django 4.2.20 on 2025-05-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
    ]
