# Generated by Django 4.2.20 on 2025-05-30 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
