# Generated by Django 4.2.20 on 2025-06-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods_imagies', verbose_name='Изображение'),
        ),
    ]
