# Generated by Django 4.2.20 on 2025-06-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_imagies', verbose_name='Изображение'),
        ),
    ]
