# Generated by Django 4.2.20 on 2025-06-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='created_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи'),
        ),
    ]
