# Generated by Django 4.2.20 on 2025-06-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='created_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи'),
        ),
    ]
